name: TTC-Soled
version: 1.0
main: com.totalcraft.soled.Main
author: PlayerSoled
description: Um Plugin Brabo

commands:
  rankup:
    description: Executa o comando de Rankup
    usage: /rankup
    executor: com.totalcraft.soled.Rankup

  tagrank:
    description: Executa o comando de set Tag Rank
    usage: /tagrank
    executor: com.totalcraft.soled.TagRank

  module:
    description: Executa o comando de Module
    usage: /module
    executor: com.totalcraft.soled.Modules

  mina:
    description: Executa o comando de Iniciar a Mina
    usage: /mina
    executor: com.totalcraft.soled.EventoMina
