name: TTC-Soled
version: 1.0
main: com.totalcraft.soled.Main
author: PlayerSoled
description: Um Plugin Brabo

commands:
  ttcsoled:
    description: Executa o comando Principal do Plugin
    usage: /ttcsoled
    executor: com.totalcraft.soled.Commands.CommandsPlugin

  rankup:
    description: Executa o comando de Rankup
    usage: /rankup
    executor: com.totalcraft.soled.Commands.Rankup

  tagrank:
    description: Executa o comando de set Tag Rank
    usage: /tagrank
    executor: com.totalcraft.soled.Commands.TagRank

  module:
    description: Executa o comando de Module
    usage: /module
    executor: com.totalcraft.soled.Commands.Modules

  mina:
    description: Executa o comando de Iniciar a Mina
    usage: /mina
    executor: com.totalcraft.soled.Commands.EventoMina

  sfly:
   description: Executa o comando de Comprar o Fly
   usage: /sfly
   executor: com.totalcraft.soled.Commands.Bfly

  jail:
    description: Executa o comando de dar Jail
    usage: /jail
    executor: com.totalcraft.soled.Commands.Jail

  unjail:
    description: Executa o comando de dar UnJail
    usage: /unjail
    executor: com.totalcraft.soled.Commands.UnJail

  vender:
    description: Executa o comando de Vender
    usage: /vender
    executor: com.totalcraft.soled.Commands.Vender

  blockprotect:
    description: Executa o comando da Proteção de blocos
    usage: /blockprotect
    executor: com.totalcraft.soled.Commands.BlockProtect

  bcollect:
    description: Executa o comando do Coletor de blocos
    usage: /bcollect
    executor: com.totalcraft.soled.Commands.CollectBlocks

  rtp:
    description: Executa o comando do Random TP
    usage: /rtp
    executor: com.totalcraft.soled.Commands.RandomTP

  banitem:
    description: Executa o comando de Banir Item
    usage: /banitem
    executor: com.totalcraft.soled.Commands.BanItem

  blocklimit:
    description: Executa o comando de Verificar blocos de limite no terreno
    usage: /blocklimit
    executor: com.totalcraft.soled.Commands.BlockLimit

  filterblock:
    description: Executa o comando de Filtro para coletar Blocos
    usage: /filterblock
    executor: com.totalcraft.soled.Commands.FilterBlock

  moises:
    description: Executa o comando de Limpar o Agua e Lava do terreno
    usage: /moises
    executor: com.totalcraft.soled.Commands.Moises

  clearchunk:
    description: Executa o comando de Limpar a Chunk
    usage: /clearchunk
    executor: com.totalcraft.soled.Commands.ClearChunk

  leilao:
    description: Executa o comando de Leilão
    usage: /leilao
    executor: com.totalcraft.soled.Commands.Leilao

  stps:
    description: Executa o comando de TPS
    usage: /stps
    executor: com.totalcraft.soled.Commands.Tps

  repair:
    description: Executa o comando de Raparar
    usage: /repair
    executor: com.totalcraft.soled.Commands.Repair

  valores:
    description: Executa o comando de Valores mínimos
    usage: /valores
    executor: com.totalcraft.soled.Commands.MinValues

  crate:
    description: Executa o comando de Crate
    usage: /crate
    executor: com.totalcraft.soled.Commands.Crate

  keys:
    description: Executa o comando de Keys
    usage: /keys
    executor: com.totalcraft.soled.Commands.Keys

  autofeed:
    description: Executa o comando de Auto Feed
    usage: /autofeed
    executor: com.totalcraft.soled.Commands.AutoFeed

  criarcomando:
    description: Executa o comando de Criar comando
    usage: /criarcomando
    executor: com.totalcraft.soled.Commands.NewCommand

  tempoafk:
    description: Executa o comando de Tempo Afk
    usage: /tempoafk
    executor: com.totalcraft.soled.Commands.TempoAfk

  setshop:
    description: Executa o comando de Setar Shop
    usage: /setshop
    executor: com.totalcraft.soled.Commands.SetShop

  ptsoled:
    description: Executa o comando de Playtime
    usage: /ptsoled
    executor: com.totalcraft.soled.Commands.PTSoled

  recompensa:
    description: Executa o comando de recompensa
    usage: /recompensa
    executor: com.totalcraft.soled.Commands.Recompensa

  recompensas:
    description: Executa o comando de recompensa
    usage: /recompensa
    executor: com.totalcraft.soled.Commands.Recompensa

  quarry:
    description: Executa o comando de achar Quarry
    usage: /quarry
    executor: com.totalcraft.soled.Commands.Quarry

  playerafk:
    description: Executa o comando de player afk
    usage: /playerafk
    executor: com.totalcraft.soled.Commands.PlayerAfk

  savegod:
    description: Executa o comando de Salvar God
    usage: /savegod
    executor: com.totalcraft.soled.Commands.SaveGod
#
#  sethome:
#    description: Executa o comando de SetHome
#    usage: /sethome
#    executor: com.totalcraft.soled.Commands.SetHome
#
#  home:
#    description: Executa o comando de Home
#    usage: /home
#    executor: com.totalcraft.soled.Commands.Home
#
#  homes:
#    description: Executa o comando de Home
#    usage: /homes
#    executor: com.totalcraft.soled.Commands.Home
#
#  delhome:
#    description: Executa o comando de Deletar Home
#    usage: /delhome
#    executor: com.totalcraft.soled.Commands.DelHome